/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.3/userguide/multi_project_builds.html
 */

rootProject.name = "test-containters-5017"
include("app")
include("app1")
include("app2")
include("app3")
include("app4")
include("app5")
include("app6")
include("app7")
